repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest compatible version
    hooks:
      - id: flake8
        additional_dependencies: []  # Optional: like flake8-bugbear, etc.
