# Generated by Django 5.2.1 on 2025-06-08 11:29

import django.db.models.deletion
from django.db import migrations, models

import apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_rating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="product/images"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, upload_to="products/images"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="products/images"
            ),
        ),
    ]
