# Generated by Django 5.2.1 on 2025-05-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_created_date_cart_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
