# Generated by Django 5.2.1 on 2025-06-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='verification_code',
        ),
    ]
