# Generated by Django 5.2.1 on 2025-06-08 11:29

from django.db import migrations

import apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0003_remove_contact_username_contact_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="banner"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="Bildirisler"
            ),
        ),
    ]
