# Generated by Django 5.2.1 on 2025-06-08 11:29

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0003_remove_contact_username_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=apps.utils.fields.CompressedImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=apps.utils.fields.CompressedImageField(blank=True, null=True, upload_to='Bildirisler'),
        ),
    ]
