# Generated by Django 5.2.1 on 2025-06-08 11:33

from django.db import migrations

import apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="avatar"
            ),
        ),
    ]
